# Generated by Django 3.1.5 on 2021-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
