# Generated by Django 3.1.5 on 2021-01-05 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210105_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
