# Generated by Django 3.1.5 on 2021-01-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Name',
            new_name='name',
        ),
    ]
