# Generated by Django 3.1.5 on 2021-01-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_member',
            name='event_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='event_member',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
